### ISSUE TITLE
Using stylish formatter?

### ISSUE THREAD

**Issue by AndrewCraswell** [TypeStrong/fork-ts-checker-webpack-plugin#119]
I'd like to use the stylish formatter that TSLint has, is this possible to do via this plugin? I only see two options for formatters described in the documentation, am I missing something simple?

**Comment by johnnyreilly** [comment]
I don't think that's supported. You can control the formatting of errors / lints using the hooks in fork-ts-checker-webpack-plugin but these are custom and I think do not take account of stylish etc. Could be wrong...

**Comment by akphi** [comment]
@piotr-oles  @johnnyreilly one thing I notice though, for a formatter like `stylish`you need to be able to group messages [like](https://github.com/palantir/tslint/blob/master/src/formatters/stylishFormatter.ts) [these](https://github.com/eslint/eslint/blob/master/lib/cli-engine/formatters/stylish.js), so their `format` functions take in array of messages whereas `fork-ts-checker-webpack-plugin` currently only [sends one message at a time](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/src/formatter/codeframeFormatter.ts) to formatter. Apparently the code is written [that way](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/blob/master/src/index.ts#L903) and there's no option to change this behavior, so writing a formatter like `stylish` is quite impossible.

Also, right now the warning/error output is quite noisy due to this. We would see double messages like this:

```
WARNING in some/path/file.js
WARNING in some/path/files.js(123:45)
123:45 Cannot find name 'a'

WARNING in some/path/file.js
WARNING in some/path/files.js(124:45)
123:45 Cannot find name 'b'
```

**Comment by johnnyreilly** [comment]
Feel free to experiment! We're potentially open to this, backwards compatibility is important but we could potentially support 2 behaviours in the logging space if it seemed the result was worthwhile

**Comment by akphi** [comment]
@AndrewCraswell @johnnyreilly after playing around with [webpack-stylish](https://github.com/webpack-contrib/webpack-stylish) for a while I realize that it's not that hard to implement a stylish-like reporter. What we can do is to create our own webpack plugin like `webpack-stylish` to format the `stats`. We should also disable errors and warnings stats for `webpack-dev-server` to avoid duplications (I also implement a custom formatter for `TsForkCheckerWebpackPlugin` to prep the messages in the way I want, so that it plays nicely with my custom plugin)

The whole thing just takes less than 100 lines of code so I figure it's totally fine not to have this feature here in this library, but if somebody really needs it, I can give it a shot.
