### ISSUE TITLE
No TypeScript errors in webpack-dev-server 

### ISSUE THREAD

**Issue by igogrek** [TypeStrong/fork-ts-checker-webpack-plugin#26]
Hello. Thanks for the great plugin - really helped us speed up the build.

We use it together with HappyPack as it's done here: 
https://github.com/TypeStrong/ts-loader/tree/master/examples/happypack  

Works great with `webpack` but TypeScript errors aren't showing in `webpack-dev-server` (we generally use it with `overlay` option which displays errors in a way they cannot be ignored).

Is there a way to fail dev-server build with fork-ts-checker?

**Comment by piotr-oles** [comment]
Sorry for the delay, I was very busy :/ I will take a look at this today, promise :)

**Comment by piotr-oles** [comment]
It's because of the design - this plugin works asynchronously in watch mode and doesn't block emit. Because of that, webpack is not aware of errors - they are logged to the console directly by the plugin.

It's because it was created for our project which has an over 100k LOC and it didn't make sense to block emit when type checking is always longer.

I see that there is a lot small and middle-sized projects that use this plugin and there it make sense so I will add `async` flag in the next PR. 

There is also hook API - you can check out @johnnyreilly notification plugin: https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin - it doesn't block emit :)

**Comment by develar** [comment]
(Hint: ... and in the IDE like Webstorm/IDEA there is an option in the Typescript tool window "Compile All" to see all errors in the project).

**Comment by piotr-oles** [comment]
Released as v0.2.5 - please upgrade and add `async: false` in plugin options - it should solve your issue :)
