### ISSUE TITLE
5.0.0-alpha.11 changes to referenced projects are not reflected

### ISSUE THREAD

**Issue by jdanil** [TypeStrong/fork-ts-checker-webpack-plugin#432]
## Current behavior
- Need to run `tsc --build` before `webpack` to build referenced projects.
- Changes made to the referenced projects appear to recompile but are not reflected after refresh.

## Expected behavior
Running `webpack` should compile project and referenced projects. Changes made to referenced projects should be recompiled and included in the updated bundles.

## Steps to reproduce the issue
1. `git clone`
1. `yarn install`
1. `cd packages/app`
1. `yarn start`
   - fails. need to `tsc --build` first.
1. `yarn compile`
1. `yarn start`
   - runs successfully now.
1. open up localhost in the browser
1. edit `app/src/index.tsx`
   - changes are reflected in the browser with hot reloading
1. edit `lib/src/index.tsx`
   - terminal shows referenced project is recompiled
   - changes are not reflected in the browser, even after refresh

## Issue reproduction repository
https://github.com/jdanil/fork-ts-checker-project-references

## Environment
 - **fork-ts-checker-webpack-plugin**: 5.0.0-alpha.11
 - **typescript**: 3.9.3
 - **eslint**: N/A
 - **webpack**: 4.43.0
 - **os**: Windows 10

**Comment by piotr-oles** [comment]
Hi @jdanil ,
Thank you for reporting this issue.
I think it's not an issue with the `fork-ts-checker-webpack-plugin`, but with the `ts-loader`. This plugin only checks if there are type errors - it doesn't emit anything. I checked your reproduction repository and it looks like the type checking works well.

The workaround for this issue is to provide `resolve.alias` to the referenced package in the `webpack.config.js` file

**Comment by piotr-oles** [comment]
You can try this one: https://github.com/microsoft/webpack-project-references-alias

**Comment by jdanil** [comment]
Brilliant! I tested it out with that library and it has addressed both those issues.
Completely missed the fact that `fork-ts-checker-webpack-plugin` is just handling type checking 🤦 
Thanks for your help @piotr-oles 🙂
