### ISSUE TITLE
Differences in watch mode and non-watch mode

### ISSUE THREAD

**Issue by donaldpipowitch** [TypeStrong/fork-ts-checker-webpack-plugin#50]
Hi!

Thank you for the cool plugin. It would be nice, if the README could mention some differences when this plugin is used in watch mode (`webpack(options).watch`) and non-watch mode (`webpack(options).run`).

E.g. we use `new ForkTsCheckerWebpackPlugin({ silent: true })`. This will log errors in non-watch mode, but it will not log errors in watch mode. To log errors in both cases with webpacks native logging we need to set `new ForkTsCheckerWebpackPlugin({ silent: true, async: false })`. Are there more differences?

**Comment by johnnyreilly** [comment]
This is interesting to know. Presumably `async: false` is useful for the production build as errors will be reported but less useful for watch mode where it will slow things down?

**Comment by donaldpipowitch** [comment]
> where it will slow things down?

I wonder how much? Our build config is very generic, so we can also support non-typescript projects. I'd like to keep all kind of projects in sync as much as possible(and also like to experiment with custom logging). So it seemed to be the best solution to use `async: false` so my logging and the general behaviour stays the same for watch/non-watch mode and for ts/non-ts projects.

**Comment by piotr-oles** [comment]
It all depends on the size of the project. On small project `async: false` works great, but in bigger it slows incremental build. For example in our project that has above 100k LOC build takes around 5 seconds but type checking around 20 seconds. An incremental build has O(1) time complexity, type checking - O(n), where n is a size of a project.

It's a good idea to add this note to the README.md. Differences between async: true and false are:
 * logging error by webpack in async: false (not console.log with formatter)
 * error exit code in async: false if errors occurred

Feel free to create PR, I can also add this note but it will take time because I'm very busy :/

**Comment by donaldpipowitch** [comment]
> but it will take time because I'm very busy :/

Don't worry about that 😃

**Comment by johnnyreilly** [comment]
Come on @donaldpipowitch - you've got a docs PR in you I'm sure :wink:

**Comment by donaldpipowitch** [comment]
Sure! 😘😃
