### ISSUE TITLE
Configuration in JS

### ISSUE THREAD

**Issue by vladimir-rovensky** [TypeStrong/fork-ts-checker-webpack-plugin#51]
Hey Everyone,

Would it be possible to add some means to configure the typescript options in JavaScript rather than loading them from tsconfig.json? We have many builds that require different setup - for instance one build shouldn't build unit tests, while another should. One build should resolve a particular module using a generated d.ts file, while another should use the actual source code of that module. On top of that, we have about ten apps that we develop, so this adds up very quickly, leading to a myriad of tsconfig.json files just to configure this one plugin.

If we could specify the typescript options (compilerOptions and files/include in particular) directly in webpack.config.js, none of this would be necessary and the whole process would be much simpler.

**Comment by johnnyreilly** [comment]
I'm not a maintainer of this project but I know PRs are welcome. Why don't you submit one with your proposed changes in? It might need a few iterations to get right but that would be a great place to start!

**Comment by piotr-oles** [comment]
I didn't add such option because I think it's not useful in most cases. Having tsconfig.json has its benefits - if you have IDE that supports typescript, it will use this file, not configuration from webpack - so IDE messages will be the same as in webpack output and whole developing process will be more consistent :) But as @johnnyreilly said - PR's are welcome :)
