### ISSUE TITLE
Throw errors inside browser overlay

### ISSUE THREAD

**Issue by DimitryDushkin** [TypeStrong/fork-ts-checker-webpack-plugin#530]
## Feature motivation
I think it will be helpful to show errors not just in console, but also in disposable overlay within web-page. I've seen https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin, but it is not working with remote development.

Probably it's already done with some tools, but I cannot find examples.

## Feature implementation
Maybe something like https://github.com/smooth-code/error-overlay-webpack-plugin, but not so fullscreeny.

**Comment by KocaHocTpa2** [comment]
+1

**Comment by piotr-oles** [comment]
We already send errors to webpack-dev-server (that's why you see them in the console), there is also plugin hook to receive them. I don't think that implementation of displaying errors in the browser should be a part of this plugin. I can help if you need any guidance in developing such a tool/plugin, but I will close this issue because it's not something that will be implemented in this plugin. So feel free to ask in this issue if you need any help :)
