### ISSUE TITLE
Expose TypeScript program

### ISSUE THREAD

**Issue by aspirisen** [TypeStrong/fork-ts-checker-webpack-plugin#568]
## Feature motivation

Sometimes in case if you develop some custom functionality you need access to TypeScript API
I can create separate TS `Program` in my plugin, but I suppose that it will cause work duplication by this and my plugin

## Feature description

Users will be able to use TypeScript compiler API

## Feature implementation

Maybe we can add TS `Program` to current hooks callback or maybe create another one

**Comment by piotr-oles** [comment]
I don't think it's easy to implement, because type-checking is done in a separate process. I can't send typescript program instance via IPC. I could create a hook that gets list of modules to require in a forked process and then passes TypeScript program to function exposed by these modules, but it would add complexity to the plugin. I would wait for more demand for this feature before implementing this.

**Comment by aspirisen** [comment]
Yeah, just interested, is it possible to set in config not function but path to file, so it could be imported in that forked process?

**Comment by piotr-oles** [comment]
Technically it's possible, but not implemented :)

**Comment by aspirisen** [comment]
Ok thanks) will wait for further requests

**Comment by Zn4rK** [comment]
I'm interested in this as well. A hook with a list of modules seems like a reasonable way of solving it.

**Comment by piotr-oles** [comment]
After more though I think I will not add this feature. I have to limit amount of features that this plugin has to be able to maintain it in a longer run :)

**Comment by XinChou16** [comment]
I'm interested in this as well, we want use the compiler API to lint .ts files in another plugin.
