### ISSUE TITLE
Use caches for module resolution and type reference directives when using compiler default functions

### ISSUE THREAD

**Issue by johnnyreilly** [TypeStrong/fork-ts-checker-webpack-plugin#598]
Hey @piotr-oles 

I just wanted to give you a heads up as to this feature being added by @sheetalkamat to `ts-loader`:

https://github.com/TypeStrong/ts-loader/pull/1287

Is it possible that some of this could be useful for `fork-ts-checker-webpack-plugin`?

**Comment by piotr-oles** [comment]
Hmmm... If I understand correctly, the compiler host created by `ts.createCompilerHost()` or `ts.createWatchCompilerHost()` has built-in cache for `resolveModuleNames()` and `resolveTypeReferenceDirectives()` but if you overwrite these methods, you will lost the cache mechanism. If that's the case, it will not improve the performance of this plugin, because we don't overwrite these methods :)

**Comment by johnnyreilly** [comment]
Ah well - good to check though!
