### ISSUE TITLE
files from `node_modules` getting resloved despite being in `.eslintignore`

### ISSUE THREAD

**Issue by olessavluk** [TypeStrong/fork-ts-checker-webpack-plugin#606]
Hi 👋

After updating to 6.2.6 which includes https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/602 I've got this error https://github.com/eslint/eslint/issues/14533. My config is: 
```
eslint: {
    files: ['**/*.{js,jsx,ts,tsx}'],
},
```

But I also have `node_modules` ignored and when running from CLI `yarn eslint --fix '**/*.{js,jsx,ts,tsx}'` it works just fine.

Do you think it can be fixed? Or maybe I can specify this blob differently to not include node_modules in the first place?

**Comment by ratherblue** [comment]
Having this issue as well. Just tried upgrading `@nuxt/typescript-build` from `^2.0.3` to `^2.1.0` and our build is broken with this same error after `fork-ts-checker-webpack-plugin` changed from `5.1.0` to `6.1.1`. We have `node_modules` ignored everywhere but it still tries to check the folder.

**Comment by ratherblue** [comment]
Alright, narrowed it down. Calling `engine.isPathIgnored(path)` calls this code in ESLint:

```
isPathIgnored(filePath) {
    const {
        configArrayFactory,
        defaultIgnores,
        options: { cwd, ignore }
    } = internalSlotsMap.get(this);
    const absolutePath = path.resolve(cwd, filePath);

    if (ignore) {
        const config = configArrayFactory
            .getConfigArrayForFile(absolutePath)
            .extractConfig(absolutePath);
        const ignores = config.ignores || defaultIgnores;
        return ignores(absolutePath);
    }
    return defaultIgnores(absolutePath);
}
```

This calls ESLint's `configArrayFactory` which tries to load configuration for that file. If you try to run `isPathIgnored` on a file in `node_modules` containing an ESLint config you don't have installed locally the check will fail. So for example in my project when it tries to check if `/app/node_modules/@babel/preset-modules/lib/index.js` is ignored (which it is), it still loads the config for that project from the `package.json` file which contains this:

```
"eslintConfig": {
  "extends": "developit",
  "rules": {
    "no-console": 0,
    "new-cap": 0
  }
},
```

I don't have the `developit` configuration, so now my build fails.

In #602 the check for `!engine.isPathIgnored(path)` was moved from only checking changed files to all files that fall under the `files` glob match. This typically includes files inside `node_modules` unless your `files` glob is specific enough to not include any `node_modules` folders.

Until this bug is fixed it you have to either:

A) Downgrade to a version that doesn't include the changes from #602 

or

B) Change your `files` glob to be very specific to avoid the `node_modules` directory entirely. Ignoring `node_modules` does not fix this issue.

**Comment by piotr-oles** [comment]
@ratherblue thanks for debugging it. Feel free to create a PR. If you don't have time, I will do it when I find a moment :)

**Comment by ratherblue** [comment]
I can try to take a stab tomorrow morning 👍.
