### ISSUE TITLE
Changing files in one entry triggers check in another webpack entry point

### ISSUE THREAD

**Issue by Melzmr** [TypeStrong/fork-ts-checker-webpack-plugin#626]
First of all thank you for working on this plugin and fixing this issue https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/558

However, I noticed another problem with the plugin v6+

## Current behavior
Let's say we have 2 different entry points of webpack config.
`firstEntry.ts` – client bundle
`secondEntry.ts` – server bundle
And we run two parallel `npm run watch` scripts. 
In case of changing something in `firstEntry.ts` file, checks are triggered in both `watch` scripts.

## Expected behavior
Changing something in `firstEntry.ts` should only trigger TS check in this particular webpack entry.

P.S. In v.5.2.1 it works as it should. TS checker runs only for the changed entry point.

## Steps to reproduce the issue
1. Open two terminal windows
2. Run `npm run watch:first` in first window
3. Run `npm run watch` in second window
4. Notice how change in `firstEntry.ts` file also triggered check in second terminal window (`secondEntry.ts`)

## Issue reproduction repository
https://github.com/Melzmr/excluded-558

## Environment
 - **fork-ts-checker-webpack-plugin**: ^6.2.12
 - **typescript**: ^4.2.4
 - **eslint**: none
 - **webpack**: ^5.36.2
 - **os**: MacOS 11.3
 
Now:
 
![image](https://user-images.githubusercontent.com/38521674/122638598-b2343000-d0fd-11eb-8568-d2c6c0230403.png)

Before:

![image](https://user-images.githubusercontent.com/38521674/122638639-f0c9ea80-d0fd-11eb-9c84-8f752db66084.png)

**Comment by piotr-oles** [comment]
It's an intentional behavior - the plug-in tries to mimic tsc as much as it's possible. The changes in v6 that triggers build on unrelated files changes from the webpack perspective fixes watch issues with type-only files. In previous versions if you had type-only file, it was not included in the dependencies set and therefore was not watched.
In general, the issue comes from the fact that TypeScript project have different semantics than webpack project and they are not compatible. The current solution favors TypeScript semantics where project is a set of files that matches pattern from tsconfig file (not dependency graph like in webpack)

**Comment by Melzmr** [comment]
@piotr-oles Oh, I see. Thanks for the explanation!
