### ISSUE TITLE
webpack watch mode will not update d.ts files when mode = write-dts

### ISSUE THREAD

**Issue by giladv** [TypeStrong/fork-ts-checker-webpack-plugin#689]
## Current behavior
might be by design - but right now, when ``mode: 'write-dts'`` (and ``build: true``) it will create d.ts files on first run iteration.
but on subsequent runs caused by files changed (webpack watch mode) it will not update the d.ts files.

## Expected behavior
update d.ts files chaned on each subsequent run caused by files changed (webpack watch mode)

## Steps to reproduce the issue
described above

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.5.0
 - **typescript**: 4.4.3
 - **webpack**: 5.52.1
 - **os**: osx 11.6

**Comment by luciopaiva** [comment]
I have a similar problem, but not exactly the same. Using TS-loader with `transpileOnly: true` and this plugin with `{ typescript: { mode: "write-dts" }}` is was not getting any `.d.ts` files, not even in the first watch pass.

I went googling for some help and, after finding your issue, I added `build: true` to my options and it is now generating `.d.ts` files as intended. Not only in the first watch pass, but in all subsequent changes as well 🤔 

I'm not sure why `build` is needed, but it's now working fine 🤷 

My env:

- fork-ts-checker-webpack-plugin: 6.5.0
- typescript: 4.5.4
- webpack: 5.65.0
- os: osx 10.15.7

**Comment by longlostbro** [comment]
"write-dts" mode is not working for me either. No d.ts file is being generated. Not even by adding the build: true option.
Could someone provide a minimal repo example of the write-dts option?

**Comment by gautamits** [comment]
Same for me @longlostbro . Anyone got to generate .d.ts files successfully ?

 - "webpack": "4.46.0"
-  "fork-ts-checker-webpack-plugin": "6.5.0"
- "typescript": "^4.1.5"

**Comment by longlostbro** [comment]
I added an inline plugin subscribing to the compiled (or whatever) event.
So after its done building i generate d.ts using tsc.

**Comment by gautamits** [comment]
Thanks @longlostbro. Which plugin you are using ? Can you please share solution with code ?

**Comment by piotr-oles** [comment]
Could you try with the newest version of the plugin? I think I found the bug and fixed it

**Comment by gautamits** [comment]
Tried with latest version and it worked. Thanks @piotr-oles .

**Comment by JiangChengen** [comment]
I know what the possible problem is now.
- fork-ts-checker-webpack-plugin： 9.0.2
- webpack: 5.89.0
- typescript: 5.2.2
Referring to this configuration, you can generate a d. ts file:
![image](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/assets/35300738/9b9fdfbe-f35f-4fa5-98bc-58a1ececcbd1)
![image](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/assets/35300738/a5cbb412-e753-4f8e-9ec2-fd377a23ff33)

关键在于这个配置：` configOverwrite`，Because the default value for this configuration is written in the document as follows:
![image](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/assets/35300738/d986263f-306a-4870-abdf-cb8230b1aa10)
'declaration 'is not declared，So you need to add it
