### ISSUE TITLE
Do not check the package of webpack externals 

### ISSUE THREAD

**Issue by kingller** [TypeStrong/fork-ts-checker-webpack-plugin#717]
## Current behavior
When I install package A in node_modules, and set it to webpack's externals, it still check the file of package A.

## Expected behavior
Skip the check for package A?

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.5.0
 - **typescript**:4.2.4
 - **eslint**: 8.6.0
 - **webpack**: 5.65.0
 - **os**:  macOS Big Sur 11.6

**Comment by piotr-oles** [comment]
This plugin [follows typescript project definition](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin#modules-resolution) from `tsconfig.json` - not webpack's dependency graph (because of performance). If you want to skip check in a given directory, you can try to add it to `exclude: []` in `tsconfig.json`
