### ISSUE TITLE
could use with esbuild-loader & vue

### ISSUE THREAD

**Issue by shenchaoran** [TypeStrong/fork-ts-checker-webpack-plugin#772]
## Current behavior

when use esbuild-loader, vue SFC is not type checked 

## Environment
 - **fork-ts-checker-webpack-plugin**: 6.5.2
 - **typescript**: 4.7.4
 - **eslint**: 8.21.0
 - **webpack**: 4.46.0
 - **os**: mac

**Comment by danparm** [comment]
Happy to make a separate issue, but I'm also not getting type checking on Vue SFCs when using `<script lang="ts" setup>`.

Using the standard `<script lang="ts">` with `defineComponent `still receives type checking.

Same behavior in v6 with webpack4 and v7 with webpack5.

**Comment by piotr-oles** [comment]
I'm dropping support for Vue.js. For the last few years, support for Vue.js has been broken, and the implementation of Vue.js integration was a hacky work-around. Unfortunately, TypeScript doesn't expose an API to do that properly, and while I created a https://github.com/microsoft/TypeScript/issues/38736 on the TypeScript repository, the TypeScript team has other priorities. As I won't have time to support this feature and am receiving justified bug reports, I believe it's better to make it clear that Vue.js is not supported by the plugin instead of pretending that it is.
